id: ACB6CCACF
base_file: fA461.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:36:16.077025
  last_modified_at: 2022-05-31 06:36:16.077039
